CREATE TABLE IF NOT EXISTS xp_prop_definitions (
  stat_type TEXT PRIMARY KEY,
  prop_family TEXT,
  expansion_phase INTEGER,
  target_status TEXT,
  priority TEXT,
  source_requirement TEXT,
  score_status TEXT,
  notes TEXT,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO xp_prop_definitions(stat_type, prop_family, expansion_phase, target_status, priority, source_requirement, score_status, notes, updated_at) VALUES
('Hitter Strikeouts','HITTER_STRIKEOUTS',1,'READY_PHASE_1','HIGH','PRIZEPICKS_PLUS_INTERNAL_CONTEXT','INTERNAL_SCAFFOLD','Phase 1 internal-only scoring first.',CURRENT_TIMESTAMP),
('Walks','WALKS',1,'READY_PHASE_1','HIGH','PRIZEPICKS_PLUS_INTERNAL_CONTEXT','INTERNAL_SCAFFOLD','Phase 1 internal-only scoring first.',CURRENT_TIMESTAMP),
('Singles','SINGLES',2,'READY_PHASE_2','MEDIUM','PRIZEPICKS_ONLY','NOT_BUILT','Component prop for total bases and fantasy score.',CURRENT_TIMESTAMP),
('Doubles','DOUBLES',2,'READY_PHASE_2','MEDIUM','PRIZEPICKS_ONLY','NOT_BUILT','Component prop for total bases and fantasy score.',CURRENT_TIMESTAMP),
('Home Runs','HOME_RUNS',2,'READY_PHASE_2','MEDIUM','PRIZEPICKS_ONLY','NOT_BUILT','Needs power/batted-ball layer later.',CURRENT_TIMESTAMP),
('Runs','RUNS',3,'READY_PHASE_3','MEDIUM','PRIZEPICKS_ONLY','NOT_BUILT','Needed before HRR and fantasy score.',CURRENT_TIMESTAMP),
('Hits+Runs+RBIs','HRR',4,'READY_LATER','LOW','COMPOSITE','NOT_BUILT','Composite prop after components mature.',CURRENT_TIMESTAMP),
('Hitter Fantasy Score','HITTER_FANTASY_SCORE',4,'READY_LATER','LOW','COMPOSITE','NOT_BUILT','Composite prop after components mature.',CURRENT_TIMESTAMP),
('Triples','TRIPLES',5,'WATCH_ONLY','LOW','PRIZEPICKS_ONLY','NOT_BUILT','Sparse event prop.',CURRENT_TIMESTAMP),
('Stolen Bases','STOLEN_BASES',5,'WATCH_ONLY','LOW','PRIZEPICKS_ONLY','NOT_BUILT','Needs catcher/pitcher/run environment later.',CURRENT_TIMESTAMP),
('Hits','HITS',3,'READY_PHASE_3','MEDIUM','PRIZEPICKS_PLUS_INTERNAL_CONTEXT','NOT_BUILT','Existing production has hits logic; expansion later.',CURRENT_TIMESTAMP),
('Total Bases','TOTAL_BASES',3,'READY_PHASE_3','MEDIUM','PRIZEPICKS_PLUS_INTERNAL_CONTEXT','NOT_BUILT','Needs hit/power context.',CURRENT_TIMESTAMP),
('RBIs','RBIS',3,'READY_PHASE_3','MEDIUM','PRIZEPICKS_PLUS_INTERNAL_CONTEXT','NOT_BUILT','Existing production has RBI logic; expansion later.',CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS xp_prop_lines_current (
  xp_line_key TEXT PRIMARY KEY,
  source_table TEXT,
  source_projection_key TEXT,
  line_id TEXT,
  player_name TEXT,
  normalized_player_name TEXT,
  team TEXT,
  opponent TEXT,
  stat_type TEXT,
  prop_family TEXT,
  line_score REAL,
  odds_type TEXT,
  start_time TEXT,
  slate_date TEXT,
  board_updated_at TEXT,
  captured_at TEXT,
  source_status TEXT,
  is_supported_single INTEGER,
  is_current INTEGER,
  is_stale INTEGER,
  target_status TEXT,
  expansion_phase INTEGER,
  imported_at TEXT DEFAULT CURRENT_TIMESTAMP,
  expires_at TEXT,
  raw_json TEXT
);

CREATE TABLE IF NOT EXISTS xp_prop_counts_snapshot (
  snapshot_id TEXT PRIMARY KEY,
  run_id TEXT,
  stat_type TEXT,
  odds_type TEXT,
  target_status TEXT,
  expansion_phase INTEGER,
  rows_count INTEGER,
  min_line REAL,
  max_line REAL,
  first_start_time TEXT,
  last_start_time TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xp_job_runs (
  run_id TEXT PRIMARY KEY,
  job_name TEXT,
  status TEXT,
  source_table TEXT,
  rows_read INTEGER DEFAULT 0,
  rows_written INTEGER DEFAULT 0,
  rows_deleted INTEGER DEFAULT 0,
  error TEXT,
  started_at TEXT DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  details_json TEXT
);

CREATE TABLE IF NOT EXISTS xp_job_logs (
  log_id TEXT PRIMARY KEY,
  run_id TEXT,
  level TEXT,
  message TEXT,
  details_json TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xp_game_bridge_current (
  xp_line_key TEXT PRIMARY KEY,
  stat_type TEXT,
  player_name TEXT,
  original_team TEXT,
  original_opponent TEXT,
  normalized_team TEXT,
  normalized_opponent TEXT,
  slate_date TEXT,
  pp_start_time TEXT,
  pp_start_time_utc TEXT,
  game_id TEXT,
  away_team TEXT,
  home_team TEXT,
  game_start_time_utc TEXT,
  time_diff_minutes REAL,
  match_status TEXT NOT NULL,
  match_method TEXT,
  candidate_count INTEGER DEFAULT 0,
  clean_match_count INTEGER DEFAULT 0,
  warning TEXT,
  built_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xp_phase1_player_metrics_current (
  xp_line_key TEXT PRIMARY KEY,
  stat_type TEXT,
  player_name TEXT,
  normalized_player_name TEXT,
  team TEXT,
  normalized_team TEXT,
  opponent TEXT,
  line_score REAL,
  odds_type TEXT,
  player_id INTEGER,
  metric_team TEXT,
  role TEXT,
  season INTEGER,
  games_logged INTEGER,
  first_game_date TEXT,
  last_game_date TEXT,
  total_pa INTEGER,
  total_ab INTEGER,
  total_hits INTEGER,
  total_rbi INTEGER,
  total_home_runs INTEGER,
  total_walks INTEGER,
  total_strikeouts INTEGER,
  last3_games INTEGER,
  last3_hits INTEGER,
  last3_ab INTEGER,
  last5_games INTEGER,
  last5_hits INTEGER,
  last5_ab INTEGER,
  last10_games INTEGER,
  last10_hits INTEGER,
  last10_ab INTEGER,
  last20_games INTEGER,
  last20_hits INTEGER,
  last20_ab INTEGER,
  season_k_rate REAL,
  season_bb_rate REAL,
  source_confidence TEXT,
  metric_match_status TEXT,
  warning TEXT,
  built_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xp_phase1_game_context_current (
  xp_line_key TEXT PRIMARY KEY,
  stat_type TEXT,
  player_name TEXT,
  normalized_player_name TEXT,
  team TEXT,
  opponent TEXT,
  normalized_team TEXT,
  normalized_opponent TEXT,
  line_score REAL,
  odds_type TEXT,
  start_time TEXT,
  slate_date TEXT,
  game_id TEXT,
  away_team TEXT,
  home_team TEXT,
  venue TEXT,
  game_status TEXT,
  lineup_slot INTEGER,
  lineup_bats TEXT,
  lineup_k_rate REAL,
  lineup_is_confirmed INTEGER,
  lineup_match_status TEXT,
  starter_name TEXT,
  starter_throws TEXT,
  starter_era REAL,
  starter_whip REAL,
  starter_strikeouts INTEGER,
  starter_walks INTEGER,
  starter_innings_pitched REAL,
  starter_match_status TEXT,
  player_id INTEGER,
  total_pa INTEGER,
  total_walks INTEGER,
  total_strikeouts INTEGER,
  season_k_rate REAL,
  season_bb_rate REAL,
  bridge_match_status TEXT,
  metric_match_status TEXT,
  context_status TEXT,
  warning_flags TEXT,
  built_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS xp_phase1_score_current (
  xp_line_key TEXT PRIMARY KEY,
  stat_type TEXT,
  player_name TEXT,
  team TEXT,
  opponent TEXT,
  line_score REAL,
  odds_type TEXT,
  game_id TEXT,
  visible_side TEXT,
  context_status TEXT,
  score_status TEXT,
  internal_score_0_100 REAL,
  internal_grade TEXT,
  base_rate REAL,
  recent_proxy_rate REAL,
  line_component REAL,
  starter_component REAL,
  lineup_component REAL,
  warning_component REAL,
  non_standard_component REAL,
  formula_json TEXT,
  warning_flags TEXT,
  score_notes TEXT,
  built_at TEXT DEFAULT CURRENT_TIMESTAMP
);
