(function(){
  function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function renderFeedStatus(rows,audit,rejected){const el=document.getElementById('feedStatus');el.innerHTML=`<h2>Screen 1 / Ingest Summary</h2><p>Accepted Legs: <b>${rows.length}</b> &nbsp; Rejected Lines: <b>${rejected.length}</b></p>`}
  function renderPoolTable(rows){const el=document.getElementById('poolMount'); if(!rows.length){el.innerHTML='<h2>Current Clean Pool</h2><p>No legs ingested.</p>';return} el.innerHTML=`<h2>Current Clean Pool</h2><div class="table-wrap"><table><thead><tr><th>#</th><th>Player</th><th>Team</th><th>Opp</th><th>Prop</th><th>Line</th><th>Type</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.idx}</td><td>${esc(r.parsedPlayer)}</td><td>${esc(r.team)}</td><td>${esc(r.opponent)}</td><td>${esc(r.prop)}</td><td>${esc(r.line)}</td><td>${esc(r.type)}</td></tr>`).join('')}</tbody></table></div>`}
  function renderHealth(h){const el=document.getElementById('healthMount'); if(!h){el.innerHTML='<h2>Daily Health</h2><p>Not loaded.</p>';return} el.innerHTML=`<h2>Daily Health</h2><p class="${h.ok?'ok':'bad'}">ok: ${h.ok} | version: ${esc(h.version||'N/A')} | status: ${esc(h.status||'N/A')}</p><div class="table-wrap"><table><thead><tr><th>Check</th><th>Value</th><th>Status</th></tr></thead><tbody>${(h.table_checks||[]).map(c=>`<tr><td>${esc(c.check)}</td><td>${esc(c.value)}</td><td>${esc(c.status)}</td></tr>`).join('')}</tbody></table></div>`}
  function branchHtml(name,arr){return`<div class="branch"><h3>${esc(name)}</h3>${(arr||[]).map(f=>`<div class="factor"><strong>${esc(f.label)}</strong><span>${esc(f.display||f.value)}</span><br><small>${esc(f.source)} | ${esc(f.confidence)}</small></div>`).join('')||'<p>No data.</p>'}</div>`}
  function renderAnalysis(vault){const el=document.getElementById('analysisMount');const items=Object.values(vault||{}); if(!items.length){el.innerHTML='<div class="card"><p>No analysis yet.</p></div>';return} el.innerHTML=items.map((v,i)=>{const packet=v.packet||{};const score=v.score||{};const matrix=(packet.matrix)||(score.packet&&score.packet.matrix)||{};const groups=matrix.groups||{};return`<article class="leg-card"><div class="leg-top"><div><h2>${esc(v.row.parsedPlayer)}</h2><p>${esc(v.row.team)} vs/@ ${esc(v.row.opponent)} | ${esc(v.row.prop)} ${esc(v.row.line)}</p></div><div><span class="pill ${v.packet_status==='ok'?'ok':'bad'}">Packet ${esc(v.packet_status)}</span> <span class="pill ${v.score_status==='ok'?'ok':'bad'}">Score ${esc(v.score_status)}</span></div></div><p>Matrix: ${esc(JSON.stringify(score.matrix_factor_summary||matrix.summary||{}))}</p><div class="matrix">${Object.keys(groups).map(k=>branchHtml(k,groups[k])).join('')}</div><details><summary>Raw Packet / Score</summary><pre>${esc(JSON.stringify({packet:v.packet,score:v.score},null,2))}</pre></details></article>`}).join('')}
  function toast(msg){console.log(msg)}
  window.UI={renderFeedStatus,renderPoolTable,renderHealth,renderAnalysis,toast};
})();
